
import { Toaster } from "sonner";
import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Az-root",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-[#172633] text-white font-mono`}
      >
        <Navbar />
        <main className="p-2 mt-4 ">
          {children}
           <Toaster richColors position="top-center" />
        </main>
      </body>
    </html>
  );
}
